# ref https://raw.githubusercontent.com/nais/naisd/master/nais_example.yaml
image: docker.adeo.no:5000/fo/veilarbmalverk
replicas:
  min: 2
  max: 2
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: veilarbmalverk/internal/isAlive
    initialDelay: 120
  readiness:
    path: veilarbmalverk/internal/selftest
    initialDelay: 120
prometheus:
  enabled: true
  path: veilarbmalverk/internal/metrics
fasitResources:
  used:
  - alias: appdynamics
    resourceType: applicationproperties
  - alias: loadbalancer:veilarbmalverk
    resourceType: loadbalancerconfig
  exposed:
  - alias: veilarbmalverkAPI
    resourceType: restservice
    path: /veilarbmalverk/api