kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbmalverk
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/veilarbmalverk/veilarbmalverk:{{version}}
  ingresses:
    - https://veilarbmalverk.nais.adeo.no
    - https://app.adeo.no/veilarbmalverk
    - https://veilarbmalverk.intern.nav.no
    - https://veilarbmalverk.prod-fss-pub.nais.io
  port: 8080
  liveness:
    path: veilarbmalverk/internal/isAlive
    initialDelay: 120
  readiness:
    path: veilarbmalverk/internal/isReady
    initialDelay: 120
  prometheus:
    enabled: true
    path: veilarbmalverk/internal/prometheus
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/appdynamics/prod
        mountPath: /var/run/secrets/nais.io/vault
  accessPolicy:
    inbound:
      rules:
        - application: veilarbpersonflate
          namespace: poao
          cluster: prod-gcp
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
