kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: veilarbmalverk
  namespace: dab
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/veilarbmalverk/veilarbmalverk:{{version}}
  ingresses:
    - https://veilarbmalverk-q1.nais.adeo.no
    - https://app-q1.adeo.no/veilarbmalverk
    - https://app-q1.dev.adeo.no/veilarbmalverk
    - https://veilarbmalverk.dev.intern.nav.no
  port: 8080
  liveness:
    path: veilarbmalverk/internal/isAlive
    initialDelay: 120
  readiness:
    path: veilarbmalverk/internal/isReady
    initialDelay: 120
  prometheus:
    enabled: true
    path: veilarbmalverk/internal/prometheus
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - kvPath: /apikey/appdynamics/dev
        mountPath: /var/run/secrets/nais.io/vault
  env:
    - name: miljo
      value: q1
