name: Deploy main
on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: write

env:
  PRINT_PAYLOAD: true

concurrency:
  group: deploy_main
  cancel-in-progress: true

jobs:
  test-build-and-push:
    permissions:
      contents: read
      id-token: write
    name: Test, build and push
    permissions:
      packages: write
      contents: read
      id-token: write # for nais docker-build-push
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - name: Build maven artifacts
        run: mvn -B package
      - name: Slack Notification (test failure)
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: 'Veilarbmalverk: tester feilet under deploy til prod'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Commit-message til feilende deploy: ${{ github.event.head_commit.message }}'
      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: pto # This is not app namespace but team which is admin in github

  deploy-dev:
    name: Deploy application to dev
    needs: test-build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: nais-dev.yaml
          VAR: image=${{ needs.test-build-and-push.outputs.image }}

  deploy-prod:
    name: Deploy application to prod
    needs: [test-build-and-push, deploy-dev]
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy application
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: nais.yaml
          VAR: image=${{ needs.test-build-and-push.outputs.image }}
      - name: Slack Notification (deploy failure)
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_USERNAME: Github Actions
          SLACK_ICON: https://github.com/github.png?size=48
          SLACK_TITLE: 'Veilarbmalverk: deploy til prod feilet'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Commit-message til feilende deploy: ${{ github.event.head_commit.message }}'
